#!/bin/sh
#
# @name BlueROV2 Heavy
#
# @type UUV
#
# @maintainer Pedro Roque <padr@kth.se>
# @maintainer Nicola De Carli <ndc@kth.se>
#

. ${R}etc/init.d/rc.uuv_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=underwater}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=bluerov_heavy}


param set-default SIM_GZ_EN 1

param set-default SENS_EN_GPSSIM 0
param set-default SENS_EN_BAROSIM 1
# TODO: add a depth sensor plugin that simulates underwater pressure measurements.
param set-default SENS_EN_MAGSIM 1

param set-default MAV_TYPE 12  # Submarine/UUV type
param set-default CA_AIRFRAME 16 # UUV airframe, added by us


# Thruster count for BlueROV2 Heavy (8 thrusters)
param set-default CA_ROTOR_COUNT 8

# Define thruster positions and moment coefficients
param set-default CA_ROTOR0_PX  0.17
param set-default CA_ROTOR0_PY  0.12
param set-default CA_ROTOR0_PZ  0.0
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.17
param set-default CA_ROTOR1_PY  0.12
param set-default CA_ROTOR1_PZ  0.0
param set-default CA_ROTOR1_KM -0.05

param set-default CA_ROTOR2_PX  0.17
param set-default CA_ROTOR2_PY -0.12
param set-default CA_ROTOR2_PZ  0.0
param set-default CA_ROTOR2_KM  0.05

param set-default CA_ROTOR3_PX -0.17
param set-default CA_ROTOR3_PY -0.12
param set-default CA_ROTOR3_PZ  0.0
param set-default CA_ROTOR3_KM -0.05

param set-default CA_ROTOR4_PX  0.17
param set-default CA_ROTOR4_PY  0.12
param set-default CA_ROTOR4_PZ -0.05
param set-default CA_ROTOR4_KM  0.05

param set-default CA_ROTOR5_PX -0.17
param set-default CA_ROTOR5_PY  0.12
param set-default CA_ROTOR5_PZ -0.05
param set-default CA_ROTOR5_KM -0.05

param set-default CA_ROTOR6_PX  0.17
param set-default CA_ROTOR6_PY -0.12
param set-default CA_ROTOR6_PZ -0.05
param set-default CA_ROTOR6_KM  0.05

param set-default CA_ROTOR7_PX -0.17
param set-default CA_ROTOR7_PY -0.12
param set-default CA_ROTOR7_PZ -0.05
param set-default CA_ROTOR7_KM -0.05


# Define electronic speed controller (ESC) function mappings for thrusters
param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104
param set-default SIM_GZ_EC_FUNC5 105
param set-default SIM_GZ_EC_FUNC6 106
param set-default SIM_GZ_EC_FUNC7 107
param set-default SIM_GZ_EC_FUNC8 108

# Set thruster output limits
param set-default SIM_GZ_EC_MIN1 1100
param set-default SIM_GZ_EC_MIN2 1100
param set-default SIM_GZ_EC_MIN3 1100
param set-default SIM_GZ_EC_MIN4 1100
param set-default SIM_GZ_EC_MIN5 1100
param set-default SIM_GZ_EC_MIN6 1100
param set-default SIM_GZ_EC_MIN7 1100
param set-default SIM_GZ_EC_MIN8 1100

param set-default SIM_GZ_EC_MAX1 1900
param set-default SIM_GZ_EC_MAX2 1900
param set-default SIM_GZ_EC_MAX3 1900
param set-default SIM_GZ_EC_MAX4 1900
param set-default SIM_GZ_EC_MAX5 1900
param set-default SIM_GZ_EC_MAX6 1900
param set-default SIM_GZ_EC_MAX7 1900
param set-default SIM_GZ_EC_MAX8 1900
